version:  '3.7'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer:4.7.4
    links:
      - mysql:mysql
    ports:
      - ${ADMINER_PORT}:8080
    restart: unless-stopped

  nginx:
    image: nginx:1.15.9-alpine
    restart: on-failure
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    links:
      - mysql
    env_file:
      - .env

volumes:
  mysql:
